### ISSUE TITLE
Access and modify particle information through each mesh element

### ISSUE THREAD

**Issue by zhangchonglin** [SCOREC/pumi-pic#108]
I am wondering if there are functions in `PUMIPic` to enable user to access and modify properties of all particles inside each mesh element. For example, if user would like to loop through each mesh element, and access or modify particle information in the following manner:

```
    // loop over all mesh elements to perform some operations on each particle in the mesh element
    auto operating_on_particle_each_cell = OMEGA_H_LAMBDA(const o::LO elm) {
        const o::LO num_particle = "number of particles in element elm"
        // loop over all particles in the current element "elm"
        for (int i = 0; i < num_particle; i++) {\
           const O::LO pid = particle index of i-th particle in element "elm"
           const o::Real Vx = particle x velocity of i-th particle in element "elm"
           some operations on other properties of i-th particle
        }
    };
    o::parallel_for(mesh->nelems(), operating_on_particle_each_cell, "operating_on_particle_each_cell");
```
is there a way to do this currently in `PUMIPic`?

In connection with this, for better data locality, `DPS` particle structure seems to be a good choice for this kind operation. Are there any functions in `DPS` particle structure to achieve this?

The above is different type of particle structure access pattern compared to the usual one:
```
    auto access_particle_structure = PS_LAMBDA(const int& e, const int& pid, const int& mask) {
      if (mask > 0) {
        // access particle information for particle with index "pid"
 
        // perform some operations on particle with index "pid"
      }
    };
    ps::parallel_for(ptcls, access_particle_structure, "access_particle_structure");

**Comment by cwsmith** [comment]
Hello.

If the particle operations within each element are not dependent on each other than the usual PS_LAMBDA will work, the `e` variable in your example will give you the element index.

Do you have a use case for performing dependent operations that would require the first form of the loop?

**Comment by zhangchonglin** [comment]
The use case for this would be if you are interested in the interaction of different particles in the same element. For example, if user would like to perform particle-particle collision within an element, including
 - A + B -> C.
 - A + B -> C+D, etc.

where A, B are different particles in the same mesh element, C and D are new particles that will be created. In this case, you need to operating on different particles at the same time, in the same mesh element . The `PS_LAMBDA` will not work in this case.

**Comment by zhangchonglin** [comment]
Yes, running two `parallel_for` will be OK as long as we can achieve this (without too much loss in performance).

Let me include all particle-particle collision scenarios and rewrite them in terms of whether the particle information will be modified (i.e. write access is required). In all cases below, write access to properties of all particles (or most particles) will be  required.

1. `A + B -> A' + B'`: where `A` and `B` can be particles of same species or different species; `A'` and `B'` are particles of same species as `A` or `B` with new properties (velocity, energy, for example) after the collision; the properties of both `A` and `B` depend on the properties of `A` and `B`.
2. `A + B -> A' + C + D`: where `A` and `B` can be particles of same species or different species; `A'` is particle of same species as `A` with new properties after the collision; `C` and `D` are new particles after the collision and will be different species compared to `A`; the properties of `A'`, `C`, and `D` depend on the properties of `A` and `B`.
3.  `A + B + C -> C' + D`: where `A`, `B`, and `C` can be particles of same species or different species; `C'` is particle of same species as `C` with new properties after the collision; `D` is a new particle after the collision and will be different species compared to `A` and `B`; the properties of both `C'` and `D` depend on the properties of `A` and `B`.
4. `A + B -> C + D`:  where `A` and `B` can be particles of same species or different species; `C` and `D` are new particles after the collision and will be different species compared to `A` and `B`; the properties of `C` and `D` depend on the properties of `A` and `B`.

In terms of the 4 cases above, you can think of them as:
1.  non chemical reaction scenario
2. dissociation reaction
3. recombination reaction
4. exchange reaction

For case `1`, `3`, and `4`, we can probably get around without creating new particles and invoke rebuild, but that's not essential.

In terms of the two `parallel_for` idea, could you elaborate that a little bit more, i.e. a pseudo code to do that. Thanks!

**Comment by cwsmith** [comment]
Thanks for the details.  Before digging into those specifics, I'd like to be clear on this question (re-phrased a bit):

- In the PS_LAMBDA a single 'thread' (of many in the parallel_for loop that uses the PS_LAMBDA) is operating on particle **pid** in element **e**. To support particle-particle interactions would you only need to read data associated with existing particles in element **e** to create/set data for new particles in element **e**?  Assume for now that we can efficiently support writing data associated with new particles in the described thread.

If my question doesn't make sense, or isn't aligned to what your asking about, we should probably schedule a call sometime next week to discuss.

**Comment by zhangchonglin** [comment]
This is resolved.
