### ISSUE TITLE
Question regarding getPIDs function

### ISSUE THREAD

**Issue by zhangchonglin** [SCOREC/pumi-pic#116]
If I understand correctly, the two returned values from the `getPIDs` function listed below should have the following sizes:
- `pids`: size is equal to `particle structure capacity`, i.e. the number of particles in the particle structure.
- `offsets`: size is equal to the `number of mesh elements + 1`.
https://github.com/SCOREC/pumi-pic/blob/7b55b1b09ec6a30695d45889fd12acf109cdb6be/particle_structs/src/ps_for.hpp#L57-L85

Are the above statements correct? If yes, then I found the `pids.size()` is not equal to `particle structure capacity` by adding a check below:
https://github.com/SCOREC/pumi-pic/blob/c26aef985b95e9cb432f424a6a3bb6089e1ad1d7/particle_structs/test/test_structure.cpp#L359-L360
@Angelyr: could you take a look at this? Thanks!

**Comment by Angelyr** [comment]
@zhangchonglin You are right about `offsets.size()`. However, `pids.size()` should be equal to the number of active particles. Then you can use `offsets(n)` will give you the start index of element n. After that `offsets(n+1)` will be the end index of element n, with no gaps in between the particles.

**Comment by zhangchonglin** [comment]
@Angelyr: thanks for the explanation Angel. I will keep this open for now until I have successfully used your function in my code.

**Comment by zhangchonglin** [comment]
@Angelyr: I have a confusion here:
- Suppose we have 4 cells, indexed as `0, 1, 2, 3`;
- the 4 cells have `2, 0, 1, 2` particles, respectively;

| Cell index | 0 | 1 | 2 | 3 |
|---------------|--- |---|---|----|
| number of particles | 2 | 0 | 1 | 2 |

What would be the content of `pids_offset` look like? I am trying to calculate the number of particles in each cell using`pids_offset`, something below?
| index of pids_offset | 0 | 1 | 2 | 3 | 4 |
|-----------------------------|---|---|---|---|---|
| pids_offset[i] | 0 | 1 | 2 |  3 | 4 |

Based on the definition, I see there could be an ambiguity on what index to use for cell with 0 particles.

Here for `cell index = 1`, there is no particle, what would be its `starting index` and `end index`? Thanks!

**Comment by zhangchonglin** [comment]
@Angelyr: thanks Angel! This makes sense now. So the previous statement `offsets(n) will give you the start index of element n`, `offsets(n+1) will be the end index of element n` is not an accurate description of the content of `offset` array. Could you update the function comment for future reference.

**Comment by Angelyr** [comment]
I updated the comment. What do think now?

**Comment by zhangchonglin** [comment]
@Angelyr: thank you Angel! This looks good. The `getPIDs` function is working well in my code.
