### ISSUE TITLE
Incorrect Kokkos usage from ctest verbose

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#14]
ctest verbose shows lines:

    Kokkos allocation "" is being deallocated after Kokkos::finalize was called
    This behavior is incorrect Kokkos usage, and will crash in future releases

Full messages:

     2: Test command: /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/mpich-3.2.1-  
                    niuhmadq72otoeruzmhwp6f7b3rqe24y/bin/mpirun "-np" "1" "./collision"
                    "/lore/gopan/pumi-pic/pumipic-  data/cube.msh"
     2: Test timeout computed to be: 10000000
     2: Kokkos allocation "" is being deallocated after Kokkos::finalize was called
     2: This behavior is incorrect Kokkos usage, and will crash in future releases

This is seen for collision, linetri_intersection and barycentric, not for adj and push_and_search . But the timeout line is there for all.

**Comment by cwsmith** [comment]
`Omega_h::Library(&argc, &argv)` calls `kokkos::initialize(...)` 

https://github.com/SNLComputation/omega_h/blob/2770abb78f2569741527cc46dfe0ab25a2e2ba9d/src/Omega_h_library.cpp#L111

and it looks like the `Library` call isn't being made for the barycentric test  (and others?):

```
pumipic (master)$ grep -r Library .
./src/unit_tests.hpp:void test_unit(Omega_h::Library *lib)
./test/test_collision.cpp:  auto lib = Omega_h::Library(&argc, &argv);
./test/test_push_and_search.cpp:  auto lib = Omega_h::Library(&argc, &argv);
./test/test_adj.cpp:  auto lib = Omega_h::Library(&argc, &argv);
```

There may also be a scoping issue if this `Library` call isn't done in `main(...)`.

**Comment by kumargp** [comment]
Solved it. Omega_h library initialization was not done first, which happened when its datatype was later added to process command line arguments. Also, when the mesh use was removed, the library initialization was also removed with it !
