### ISSUE TITLE
RHEL: Enabling OpenMP in the compiler

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#16]
pumipic compiling fails with updated trilinos. Need to pass openmp in CMake ?

Need find_package(OpenMP) ?

```
In file included from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/trilinos-develop-2zim243zetgpbtcm6swwulha65t2rxk2/include/Kokkos_OpenMP.hpp:270:0,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/trilinos-develop-2zim243zetgpbtcm6swwulha65t2rxk2/include/Kokkos_Core.hpp:57,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/omega-h-9.19.1-aoj4yifeajy3psf2keefnjjclpzlc2ll/include/Omega_h_kokkos.hpp:20,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/omega-h-9.19.1-aoj4yifeajy3psf2keefnjjclpzlc2ll/include/Omega_h_stack.hpp:8,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/omega-h-9.19.1-aoj4yifeajy3psf2keefnjjclpzlc2ll/include/Omega_h_for.hpp:5,
                 from /lore/gopan/pumi-pic/src/pumipic_adjacency.hpp:6,
                 from /lore/gopan/pumi-pic/test/test_collision.cpp:2:
/opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/trilinos-develop-2zim243zetgpbtcm6swwulha65t2rxk2/include/OpenMP/Kokkos_OpenMP_Exec.hpp:51:2: error: #error "You enabled Kokkos OpenMP support without enabling OpenMP in the compiler!"
 #error "You enabled Kokkos OpenMP support without enabling OpenMP in the compiler!"
  ^~~~~
make[2]: *** [test/CMakeFiles/collision.dir/test_collision.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/collision.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cwsmith** [comment]
I'll push changes to the build system to resolve this in a few hours.  If you need to build on rhel7 sooner than that I can reinstall trilinos with serial kokkos.On Jan 22, 2019 6:03 PM, Gopan Perumpilly <notifications@github.com> wrote:pumipic compiling fails with updated trilinos. Need to pass openmp in CMake ?
Need find_package(OpenMP) ?
In file included from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/trilinos-develop-2zim243zetgpbtcm6swwulha65t2rxk2/include/Kokkos_OpenMP.hpp:270:0,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/trilinos-develop-2zim243zetgpbtcm6swwulha65t2rxk2/include/Kokkos_Core.hpp:57,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/omega-h-9.19.1-aoj4yifeajy3psf2keefnjjclpzlc2ll/include/Omega_h_kokkos.hpp:20,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/omega-h-9.19.1-aoj4yifeajy3psf2keefnjjclpzlc2ll/include/Omega_h_stack.hpp:8,
                 from /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/omega-h-9.19.1-aoj4yifeajy3psf2keefnjjclpzlc2ll/include/Omega_h_for.hpp:5,
                 from /lore/gopan/pumi-pic/src/pumipic_adjacency.hpp:6,
                 from /lore/gopan/pumi-pic/test/test_collision.cpp:2:
/opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/trilinos-develop-2zim243zetgpbtcm6swwulha65t2rxk2/include/OpenMP/Kokkos_OpenMP_Exec.hpp:51:2: error: #error "You enabled Kokkos OpenMP support without enabling OpenMP in the compiler!"
 #error "You enabled Kokkos OpenMP support without enabling OpenMP in the compiler!"
  ^~~~~
make[2]: *** [test/CMakeFiles/collision.dir/test_collision.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/collision.dir/all] Error 2
make: *** [all] Error 2

**Comment by kumargp** [comment]
A day is not a problem.

**Comment by cwsmith** [comment]
The `particle_structs` branch builds with the SCOREC/particle_structures repo using the following modules:
```
gcc/7.3.0-bt47fwr mpich/3.2.1-niuhmad cmake/3.13.1-ovasnmm trilinos/develop-debug-openmp-ackkufk omega-h/9.19.1-sj27mkl
```

The master branch will build with serial kokkos (now with kokkos debugging (e.g., bounds checks) enabled:

```
gcc/7.3.0-bt47fwr mpich/3.2.1-niuhmad cmake/3.13.1-ovasnmm
trilinos/develop-debug-j5qmm43 omega-h/9.19.1-4k5kja4
```

**Comment by cwsmith** [comment]
I was able to build and run the master branch with the serial kokkos/trilinos module.  Please reopen this if there are problems building with the new modules.

Note, the following commits rename envRhel7OpenMP.sh to envRhel7Serial.sh and update the module list.
https://github.com/SCOREC/pumi-pic/commit/a7a77422ccccc84f2d25d75d603e83fb36c6c0c9
https://github.com/SCOREC/pumi-pic/commit/4b6e0ee255666fed463484efb83e751cdddffc36
