### ISSUE TITLE
Using particle_structure

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#21]
Trying to use SCS in pumipic_adjacency.hpp.

pumi-pic/src/pumipic_adjacency.hpp:10:10: fatal error: psTypes.h: No such file or directory
 #include <psTypes.h>
          ^~~~~~~~~~~
          
 Error [here](https://github.com/SCOREC/pumi-pic/blob/dist2bdry/src/pumipic_adjacency.hpp#L10)

Is there any settings I am missing ?

**Comment by diamog** [comment]
You shouldn't need to include psTypes.h. This file was used for the pseudo-push when we were testing particle structures. You should only need SCS_Macros.h, SellCSigma.h, and MemberTypes.h

**Comment by kumargp** [comment]
The error is still there for SellCSigma.h

pumi-pic/src/pumipic_adjacency.hpp:11:10: fatal error: SellCSigma.h: No such file or directory
 #include <SellCSigma.h>
          ^~~~~~~~~~~~~~

**Comment by diamog** [comment]
The above commit on master should fix the problem.
