### ISSUE TITLE
Using PS_PARALLEL_FOR_ELEMENTS macro

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#22]
Error when using PS_PARALLEL_FOR_ELEMENTS  in  [here](https://github.com/SCOREC/pumi-pic/blob/dist2bdry/src/pumipic_adjacency.hpp#L583):

pumipic_adjacency.hpp:[607](https://github.com/SCOREC/pumi-pic/blob/dist2bdry/src/pumipic_adjacency.hpp#L607):4: error: macro "PS_PARALLEL_FOR_ELEMENTS" passed 8 arguments, but takes just 4
   }); 

I followed similar uses [here](https://github.com/SCOREC/pumi-pic/blob/master/test/pseudoPtclToMesh.cpp#L129)

Note: I had to add #include <psTypes.h> to use Vector3d.

**Comment by diamog** [comment]
You have run into the unprotected comma problem with macros. @cwsmith had some ways to get around this issue that i can't remember now.

That being said, we have a more friendly method to perform particle loops using lambdas. You can see a simple example [here](https://github.com/SCOREC/particle_structures/blob/master/test/lambdaTest.cpp#L33-L38). I believe we will want to move to using this method as it is easier to understand compilation errors on the device.

**Comment by cwsmith** [comment]
This macro was replaced with a lambda:
https://github.com/SCOREC/particle_structures/blob/c6b14b15eb36891a7e851ff1640de32339ac1546/test/lambdaTest.cpp#L40-L45
