### ISSUE TITLE
Libraries for Handling Parameters and Fields/Data

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#23]
GITR uses libConfig for reading parameters and NETCDF for input fields and storing simulated data. Do we use the same, or any suggestions ?

**Comment by cwsmith** [comment]
Would you please be more specific about the needed functionality?

**Comment by kumargp** [comment]
There are many parameters needed for simulation. Reading those from text files could be a headache if user changes the formatting of the text file. LibConfig stores those in objects which can be easily used, and it uses structured format not sensitive to spaces etc.

An example of parameters used in GITR is at 
https://github.com/ORNL-Fusion/GITR/blob/master/examples/operatorTests/straightLine/3Dgeom/input/gitrInput.cfg

Particle initialization is not uniformly on/in domain, but at selected points, many times only one location.

And example of particle source's characteristics used for initializing particles, at 
https://github.com/ORNL-Fusion/GITR/blob/master/examples/operatorTests/straightLine/3Dgeom/input/particleSource.cfg

In GITR the fields and profiles are stored as NETCDF files. Smaller files compared to text files.

Result and intermediate steps of simulation could take considerable storage, and example https://github.com/ORNL-Fusion/GITR/blob/master/src/gitr.cpp#L4264

Handling the above data on multiple mpi ranks may be easier with NETCDF ?

I think NETCDF is very useful given that we don't know the size of input/output data. LibConfig is more of convenience rather than handling C style constants. Use of these libraries can be limited to host.

**Comment by cwsmith** [comment]
Lets implement a reader for the NETCDF field data.  I'm guessing we can make progress without worrying about managing multiple input parameters.

**Comment by kumargp** [comment]
OK . Now  There is text parsing.  CMake option needed for   netcdf.

**Comment by cwsmith** [comment]
I'm not sure I understand.

**Comment by kumargp** [comment]
It should be
"...  CMake of Gitrm(pumipic) needs to be updated to include NETCDF in compiling step."
