### ISSUE TITLE
Initialize particles only in selected element(s)

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#25]
How to initialize particles only in one or more elements ?

**Comment by cwsmith** [comment]
One approach is in the pseudo push and search test.  We start by creating an array of how many particles are in each element.  In this case the 'intitial element' (272) gets 12 particles and the rest get zero:

https://github.com/SCOREC/pumi-pic/blob/2961b977b849e5ba66e8c6e29a2694f1bb28ab8a/test/pseudoPushAndSearch.cpp#L326-L330

Then, we create the SCS using the array:

https://github.com/SCOREC/pumi-pic/blob/2961b977b849e5ba66e8c6e29a2694f1bb28ab8a/test/pseudoPushAndSearch.cpp#L344-L345

Now that we have storage for the particles in the starting element we set their coordinates to the centroid of the starting element, set their target position along the bottom inset face of the pisces geometry, then run adjacencySearch to move the particles to the starting position.  

This approach lets us place a bunch of particles without having to read in a long list of coordinates.
