### ISSUE TITLE
particle-per-element ordering not preserved with SCS full sorting

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#26]
Using classification to set the initial elements with 
https://github.com/SCOREC/pumi-pic/blob/f8c90ffcfd7f2d3fcbad90cf0d343e08d0020973/test/pseudoPushAndSearch.cpp#L440
and setting `sigma=INT_MAX` results in a shuffling of the omega_h elements assigned particles.  Running with `sigma=1` 
https://github.com/SCOREC/pumi-pic/blob/6ec9642c6af292bba56b64fc9ef855c223a93275/test/pseudoPushAndSearch.cpp#L450
maintains the assignments.

For debugging, setting the model face to 7 should assign particles to only four elements at the top of the interior cylinder.

**Comment by diamog** [comment]
The problem is here:
https://github.com/SCOREC/particle_structures/blob/master/support/SellCSigma.h#L348

A mapping from element id to the sorted ptcl_pairs structure needs to be made. I will fix it, when I get to a computer.

**Comment by diamog** [comment]
This [commit](https://github.com/SCOREC/particle_structures/commit/8805781e93357e1037f65126b391271bef2f6fb0) of particle structures should fix this error

**Comment by cwsmith** [comment]
Thank you.  With full sorting enabled the pseudoPushAndSearch test runs as expected.
