### ISSUE TITLE
Merge 3d mesh functionalities from gitrm branch 

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#39]
The pumipic 3d mesh search and utilities developed are not merged with the master branch for a while. They are maintained in the gitrm branch.  Need to merge those.

**Comment by cwsmith** [comment]
@diamog The three of us should talk about where these changes should go.  From slack:
"The files updated for gitrm are pumipic_adjacency, pumipic_utils, and unit_tests (to be updated)."

@kumargp What is `pumipic_utils`?

**Comment by kumargp** [comment]
The utils has (1) functions that are essentially a group of omega_h calls, (2) utilities such as centroid, and (3) interpolation functions that are replacements (organized) of GITR interpolation functions. Some of the GITR functions interpolation are kept in it for testing purpose, and will be deleted later.
