### ISSUE TITLE
group and plane controls in pseudoXGCm?

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#40]
Where do we specify how many processes are assigned to each group and how many planes are created in the pseudoXGCm driver?  Are the planes specified by the gyro scatter forward and backward maps here:
https://github.com/SCOREC/pumi-pic/blob/295337486ece960592546ab17b5022a57e88db7c/test/pseudoXGCm.cpp#L418

**Comment by cwsmith** [comment]
Are the groups specified in the `.cpn` file?

**Comment by diamog** [comment]
The pseudoXGCm driver does not have the concept of planes and groups. These are only within the executables of the xgcm repo.

**Comment by cwsmith** [comment]
Doh!
