### ISSUE TITLE
particle_structures: error on construction at sorting

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#43]
On AIMOS:

To define ptcls: nel 901700 nGids 901700
Constructing 1000000 Particles with sigma 2147483647 V 128
Building SCS with C: 32 sigma: 2147483647 V: 128
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 2nd step: cudaErrorInvalidValue: invalid argument
 
module use /gpfs/u/software/dcs-spack-install/v0133gccSpectrum/lmod/linux-rhel7-ppc64le/gcc/7.4.0-1/
module load spectrum-mpi/10.3-doq6u5y
module load gcc/7.4.0/1
module load cmake/3.15.4-mnqjvz6

This is on AIMOS, using 1 gpu. This is not seen on blockade.
Latest pumipic version 6f954bb included in fun3dmesh branch ff9c188.
With sorting =1, this disappears. This error was around long back, then disappeared. Now it is seen again for full sorting.

**Comment by diamog** [comment]
Can you provide what version of cuda is being used and which SM is set for the kokkos/omega_h builds. This [issue](https://github.com/thrust/thrust/issues/936) seems to point that this error could be a result of a mismatch.

**Comment by kumargp** [comment]
The cuda version is 10.1 in all the builds. Kokkos ARCH is Volta 70.
There is issue with omegah SM.
For the current omega_h build there is no SM seen, which might force default old one.
I will build the omegah with specific SM70. I can see a previous omegah build with SM70, which seems to have 
no issue with the sorting. Also, the current build has issue with mesh reading.

**Comment by kumargp** [comment]
Works when SM is specified for the omegah build.
