### ISSUE TITLE
tests hanging on blockade

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#45]
On blockade, all pumipic tests *up to* 'pseudoPushAndSearch_t1' pass following the just updated instructions here:

https://github.com/SCOREC/pumi-pic/wiki/Building-and-Running-on-SCOREC-RHEL7

`pseudoPushAndSearch_t1`, `search2d`, and `pseudoXGCm_[24kElms|scatter]` appear to hang.  There may be others.

**Comment by kumargp** [comment]
The pre-load balancing version of pumipic works without problem for GITRm. Tested with the version 
6f954bb 2020-07-16 Merge pull request #42 

Current version waits forever at the library init step 
 pumipic::Library pic_lib(&argc, &argv);

Also all the pumipic unit tests pass (except the outdated ones that I created) with the 6f954bb of pumipic.

**Comment by cwsmith** [comment]
For the record, the 'current version' is https://github.com/SCOREC/pumi-pic/tree/b8cc828453c07322c85c7ce2a082139b74c964f8 ?

**Comment by cwsmith** [comment]
Building and running pumipic (b8cc828453c07322c85c7ce2a082139b74c964f8) `ctest -V -R pseudoPushAndSearch_t1` again on blockade results in a hang.

**Comment by kumargp** [comment]
Yes, the current version I tested is b8cc828 2020-09-21.
Also noticed that the Kokkos unit test KokkosAlgorithms_UnitTest hangs, and nvidia-smi shows the same zero processing as seen in the case of pseudoPushAndSearch_t1, and GITRm built using the  pumipic b8cc828. But the pumipic 6f954bb built using the same Kokkos build, and GITRm based on these have no problem.

**Comment by cwsmith** [comment]
`pseudoPushAndSearch_t1` is hanging here:
https://github.com/SCOREC/pumi-pic/blob/b8cc828453c07322c85c7ce2a082139b74c964f8/src/pumipic_library.cpp#L18

**Comment by cwsmith** [comment]
Apparently, using `nvcc_wrapper` when there is no kokkos/cuda code to build in engpar was the cause of the hangs in `Kokkos::initialize(...)`.  We can only speculate as to why this was a problem.

https://github.com/SCOREC/pumi-pic/wiki/Building-and-Running-on-SCOREC-RHEL7/24198e420ec9cc62d5fd70230abf85b2e11c01e8

@kumargp

**Comment by cwsmith** [comment]
It appears that when linking with `nvcc_wrapper` a default, and old, CUDA `-arch` flag is passed unless cmake is specifically told to use a specific arch flag; i.e., `-DCMAKE_CXX_FLAGS=-arch=sm_75`.

**Comment by kumargp** [comment]
Another error on blockade while trying to compile Kokkos, or pumipic
cmake: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by cwsmith** [comment]
It sounds like the new cmake/3.18.3 module was loaded.  Please load an older one and try again.

**Comment by kumargp** [comment]
Correct. cmake/15 solved it.

**Comment by kumargp** [comment]
Passing arch flag solved the problem faced in using load balancer.
