### ISSUE TITLE
Finding EngPar in downstream application

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#46]
GITRm has to use explicit find call to use EngPar. This can be avoided, since it is already included in pumi-pic.

Without   bob_public_dep(EnGPar) in GITRm  CMakeLists :
 Target "GITRm" links to target "EnGPar::engpar" but the target was not
 found.  Perhaps a find_package() call is missing for an IMPORTED target, or
 an ALIAS target is missing?
CMake Error at CMakeLists.txt:29 (add_executable):
 Target "GITRm" links to target "EnGPar::pcu" but the target was not found.
 Perhaps a find_package() call is missing for an IMPORTED target, or an
 ALIAS target is missing?

With bob_public_dep(EnGPar) in GITRm  CMakeLists, but without the engpar installation path in CMAKE_PREFIX_PATH  :
CMake Error at cmake/bob.cmake:115 (find_package):
 By not providing "FindEnGPar.cmake" in CMAKE_MODULE_PATH this project has
 asked CMake to find a package configuration file provided by "EnGPar", but
 CMake did not find one.
 Could not find a package configuration file provided by "EnGPar" with any
 of the following names:
   EnGParConfig.cmake
   engpar-config.cmake
 Add the installation prefix of "EnGPar" to CMAKE_PREFIX_PATH or set
 "EnGPar_DIR" to a directory containing one of the above files.  If "EnGPar"
 provides a separate development package or SDK, be sure it has been
 installed.

**Comment by diamog** [comment]
The above commit adds the necessary variable settings for finding EnGPar downstream and has been tested to work with XGCm. Let me know if this works in GITRm as well.

**Comment by diamog** [comment]
Also as a note, there is a small change to the configuration of pumipic. The argument `-DEnGPar_PREFIX=$engpar` needs to be passed to cmake when configuring pumipic. The instruction pages have been updated accordingly
