### ISSUE TITLE
csr: test input file missing

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#48]
The input file for this test:

https://github.com/SCOREC/pumi-pic/blob/18f6d92f8a49fcadbd8c67fd7dae7f446f77e31b/particle_structs/test/testing.cmake#L38

`small_ptcls_e5_p25_r4_edit`,  is not created by one of the `write_ptcl*` tests.  

@stevespreiz Would you please upload it to the repo or, if possible, have `test_csr_small3` load the `small_ptcls_e5_p25_r4` and edit it at runtime?

**Comment by stevespreiz** [comment]
Removing this test since it is redundant.
