### ISSUE TITLE
Error converting Simmetrix mesh to Omega_h mesh

### ISSUE THREAD

**Issue by zhangchonglin** [SCOREC/pumi-pic#49]
I am having trouble converting the Simmetrix mesh (`sms/smd` files) to Omega_h mesh after successfully building `Omega_h` following this instruction: [simmetrix-to-omegah-mesh-conversion](https://github.com/SCOREC/pumi-pic/wiki/simmetrix-to-omegah-mesh-conversion).

I could perform the mesh conversion using the example: `pumi-meshes/upright/`, however using the XGC1 Cyclone mesh, I encountered the following error, without much useful information:

```
Error: Code: 904 String: ***
terminate called after throwing an instance of 'SimError*'
Aborted (core dumped)
```

Modules used:
```
Currently Loaded Modules:
  1) gcc/7.3.0-bt47fwr   2) cmake/3.15.4-kgiql7d
  3) mpich/3.3-diz4f6i   4) simmetrix-simmodsuite/14.0-190928-snlypqg
```

Could any of you try if you could perform the conversion using mesh in this location: [Cyclone_ITG_deltaf_37kmesh](https://github.com/SCOREC/xgc1_data/tree/master/Cyclone_ITG/Cyclone_ITG_deltaf_37kmesh). My suspicion is the version mismatch of Simmetrix.

**Comment by cwsmith** [comment]
Your suspicion is most likely correct; the version of SimModSuite used to build Omega_h needs to be compatible with the version of SimModeler (which is built at Simmetrix using SimModSuite C++ libraries) used to generate the mesh.  

Omega_h `cws/meshSimReader` was just updated to support SimModSuite 15.0-200714 . https://github.com/SCOREC/omega_h/commit/1235d6f22479bbedbf38dbde70935ca2fbd2c9d2

@kumargp @dhyan1272

**Comment by zhangchonglin** [comment]
Changing to `gcc7.4` and `mpich3.3.1` failed to build (just a switch of modules only), instead of using:
```
module load gcc mpich cmake simmetrix-simmodsuite/14.0-190928-snlypqg
```
now I use:
```
module load gcc/7.4.0-c5aaloy mpich/3.3.1-bfezl2l cmake simmetrix-simmodsuite/15.0-200714-x7ycno2
```
In the first case, the modules loaded are those in the previous comment.

Error message during build:
```
-- Omega_h_USE_DOLFIN: OFF
-- Omega_h_SEMVER = 9.27.0-sha.1235d6f+11011000100000
-- Omega_h_USE_SimModSuite: ON
-- Building with SimModSuite 15.0.200714
-- SIM_ARCHOS x64_rhel7_gcc48
CMake Error at cmake/FindSimModSuite.cmake:31 (message):
  simmetrix library SimPartitionWrapper-mpich3.3 not found in
Call Stack (most recent call first):
  cmake/FindSimModSuite.cmake:140 (simLibCheck)
  src/CMakeLists.txt:153 (find_package)


-- Configuring incomplete, errors occurred!
```


Side comments regarding loading `gcc7.4` and `mpich3.3.1`:
- I could only see `simmetrix-simmodsuite/15.0-200714-x7ycno2`, when I load `gcc7.4` and `mpichi3.3.1` which are not available with `module av`. I only knew them exist from words of mouth, or use `module spider gcc`.
- Any reason these are not available by default? Thanks!

**Comment by zhangchonglin** [comment]
I figured out the build issue, with `mpich3.3.1`, the `cmake` argument needs to be changed to: `-DSIM_MPI=mpich3.3.1`, instead of `mpich3.3` as in the wiki page.

The side comments I have still hold, and I would like you to take a look at that, Thanks! @cwsmith

**Comment by zhangchonglin** [comment]
Building `omega_h` with new version of SimModSuite worked for mesh conversion. The one I used are:
- Fusion mesh creation: `simmetrix-simmodsuite/15.0-200330dev-aernpnm`
- Omega_h build: `simmetrix-simmodsuite/15.0-200714-x7ycno2`

Version mismatch is just that I do not want to rebuild the Fusion mesh code (TOMMS?).

**Comment by cwsmith** [comment]
@zhangchonglin I'm guessing our messages crossed paths.  Please take a look at the build commands in [this comment](https://github.com/SCOREC/pumi-pic/issues/49#issuecomment-704320534).  Please let me know if they don't work and I'll help you resolve the problems.

An issue for module accessibility is here: https://github.com/SCOREC/rhel7-spack-config/issues/10

**Comment by zhangchonglin** [comment]
Thanks for the detailed comments regarding how the modules are managed under Spack. I was able to build `omega_h` and run the mesh conversion tool as in early comments.
