### ISSUE TITLE
Particle Distribution Generation Time

### ISSUE THREAD

**Issue by stevespreiz** [SCOREC/pumi-pic#50]
For large test cases in `performance_tests/ps_rebuild.cpp` the time to run on the Gaussian and Exponential distributions is excessively long especially when compared to the uniform distribution. I believe this is because the random generator gets hung up on the do...while loop at:

https://github.com/SCOREC/pumi-pic/blob/d377ab3ae93451b72d34fa37deb465136c89d8c6/particle_structs/test/Distribute.cpp#L64

and also line 86. This makes running large test cases (>500k particles) on these distributions not practical though these tests are desired.

**Comment by zhangchonglin** [comment]
Do you have a rough time of how long does it take to sample, for example 1 million particles?

I am not familiar with what's being done in this code for particle initialization, but what does the term `Gaussian` or `Exponential distribution` in the code referring to: in terms of particle location, velocity, or other particle property?

A more efficient way to sample a distribution would be to use `acceptance-rejection` sampling method, compared to a naive sampling method, see for example: [Rejection sampling
](https://en.wikipedia.org/wiki/Rejection_sampling)

**Comment by diamog** [comment]
Sorry for the late reply. I lost power from the storm. After running through some tests, I've concluded the main reason the distribution is slow is due to it being performed on the CPU. When initially designed it was meant to be run once to generate a data set which was fast enough, but being run per iteration it is now a bottleneck. I will implement GPU versions of the distribution functions which should alleviate the slowdown

**Comment by diamog** [comment]
The above commit adds GPU distribution functions for even, uniform, and Gaussian. Exponential is harder to get on the GPU and will likely require some direct CUDA calls so it will take more time, for now it calls the slow CPU version.

**Comment by diamog** [comment]
The above commit adds an "exponential" distribution algorithm on the GPU. As a side note, this distribution is not technically an exponential distribution, but instead a Poisson discrete distribution with exponential bin lengths which gives the desired distribution we want to test.
