### ISSUE TITLE
Unnessesary Functions in CSR

### ISSUE THREAD

**Issue by MatthewChristoff** [SCOREC/pumi-pic#57]
I noticed that CSR has the [following](https://github.com/SCOREC/pumi-pic/blob/6b7cde783e9fa067edd57b38f70f686093274c29/particle_structs/src/csr/CSR.hpp#L69) 4 functions implemented, and I don't think they should exist:

```
lid_t getNumPtcls() { return num_ptcls; }
kkLidView getOffsets() { return offsets; }
MTVs getPtcl_data() { return ptcl_data; }
lid_t getCapacity() { return capacity_; }
```

`getNumPtcls()` and `getCapacity()` already have equivalents [inherited](https://github.com/SCOREC/pumi-pic/blob/6b7cde783e9fa067edd57b38f70f686093274c29/particle_structs/src/particle_structure.hpp#L37) from `particle_structure`.
`getOffsets()` and `getPtcl_data()` expose private member variables. 

I'm aware that `getPtcl_data()` is currently being [called](https://github.com/SCOREC/pumi-pic/blob/6b7cde783e9fa067edd57b38f70f686093274c29/particle_structs/test/test_csr.cpp#L136) in `test_csr.cpp`, but I'm not sure where else these functions are called from.

**Comment by diamog** [comment]
I'm going to clean up the CSR implementation and take care of these functions along with that.
