### ISSUE TITLE
failing ctests

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#70]
Merging the `fun3dmesh` branch adds (?) two failing tests:

```
26 - barycentric_4 (Failed)
27 - linetri_intersection_2 (Failed)
```

Some more info on the merge is here:
https://github.com/SCOREC/pumi-pic/pull/65#issuecomment-828895814

Do we care about these tests?  They were failing in `fun3dmesh` prior to the merge so I suspect they have been broken for some time.

**Comment by diamog** [comment]
I believe we previously determined we don't care about those tests. I see no problem removing them.

**Comment by cwsmith** [comment]
The failing tests were removed.
