### ISSUE TITLE
measuring device memory usage

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#71]
The `particle_structs/test/destroy_test.cpp` and `test/pseudoXGCm.cpp` call `cudaMemGetInfo` to check device memory usage:

https://github.com/SCOREC/pumi-pic/blob/dcf019a5ff28832ba275fe0b21fe59b0a7bbb9a3/particle_structs/test/destroy_test.cpp#L63

There are two issues with this:
- it measures usage for all processes using the device instead of just the calling process
- it uses the cuda runtime api; i.e., it is not portable to intel, amd, etc..

The first issue results in the `destroy_test` failing when another process uses device memory during execution of the region we monitor for no leaks.

The Kokkos developers suggested trying to register a callback as shown here:

https://github.com/kokkos/kokkos/blob/1fb0c284d458c75370094921d9f202c287502325/core/unit_test/tools/TestLogicalSpaces.hpp#L63-L71

This capability exists in Kokkos 3.2.00 and newer.

**Comment by Angelyr** [comment]
This has been replaced with memory testing.
