### ISSUE TITLE
omega_h classification info incorrect after picparts created

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#75]
Following up on https://github.com/SCOREC/omega_h/issues/21.

Some testing with GITRm found that calling omegah `ask_revClass(2)` after picparts were created, on the omegah mesh from the picparts, caused a huge slowdown in performance (<1 second to > 250 seconds).  Before picparts are created the performance of `ask_revClass(2)` is fine.

```
Time in rev class4.18175 min.

TOP-DOWN:
=========
ask_revClass 250.905 2
|  derive_revClass 250.905 1
|  |  sort_by_high_index 250.903 1
|  |  Write allocation 0.0002082 4
|  |  offset_scan 0.000120076 1
|  |  |  Write allocation 5.1748e-05 1
|  |  |  device_free 1.5294e-05 1
|  |  |  single host to device 1.3548e-05 1
|  |  |  device_malloc 1.0066e-05 1
```

@dhyan1272 Would you please post the link to the gitrm branch with the call to `ask_revClass(2)` that we tested with?  We'll try to create a reproducer from it (or debug with it directly).

**Comment by dhyan1272** [comment]
The rev classification API called on mesh after returned from pic parts.
https://github.com/SCOREC/gitrm/blob/gitrm_rev_class/src/GITRm.cpp#L224
https://github.com/SCOREC/gitrm/blob/gitrm_rev_class/src/GITRm.cpp#L229

**Comment by cwsmith** [comment]
@dhyan1272 Thanks for the link.  In the test we ran yesterday, was was the value of the `nlayers` command line argument?

https://github.com/SCOREC/gitrm/blob/79b55abeba336fae64c7bc24dce166dc2e6705dd/src/GITRm.cpp#L176

**Comment by dhyan1272** [comment]
It's 5 layers

**Comment by cwsmith** [comment]
https://github.com/SCOREC/pumi-pic/commit/571b2b085a3eee895d29620e5b1059d470e454cf reproduces the problem on a 7k cube mesh. 

```
43: Time in rev class (omegah mesh) 0.00123084 seconds 
43: Ngraph global stats <vtx edges pins>: 2 1 1
43: done picparts
43: Time in rev class (pumipic->omegah mesh) 1.49869 seconds
```

**Comment by cwsmith** [comment]
@diamog When you return, I think we'll need help with this.

**Comment by cwsmith** [comment]
With https://github.com/SCOREC/pumi-pic/commit/d4b0a400092fdf26f9f44613824b0203d9874779 the timings (built with `CMAKE_BUILD_TYPE=debug`)  in `ask_revClass` after picpart creation look better.

```
Time in rev class (omegah mesh) 0.00115147 seconds
Ngraph global stats <vtx edges pins>: 2 1 1
done picparts
Time in rev class (pumipic->omegah mesh) 0.00780723 seconds

TOP-DOWN:
=========
ask_revClass 0.0089559 2
|  derive_revClass 0.00895087 2
|  |  sort_by_high_index 0.00850231 2
|  |  Write allocation 0.000104547 8
|  |  offset_scan 6.9708e-05 2
|  |  |  Write allocation 2.5508e-05 2
|  |  |  device_free 1.283e-05 2
|  |  |  single host to device 5.51e-06 2
|  |  |  device_malloc 5.26e-06 2
```

@dhyan1272 Can you rebuild pumipic and gitrm and test again?

**Comment by dhyan1272** [comment]
```
Time in rev class:0.072384 min (for the ~150k elements mesh) : the picparts mesh
Time in rev class: 14.4446 min  (for the ~11.4 million elements mesh): the omega-h mesh returned by picparts from pumi-pic
Time in rev class: 5.94557 min  (for the ~11.4 million elements mesh): the full/original omega-h mesh
```

**Comment by cwsmith** [comment]
@dhyan1272 Thank you.

I ran the 150k mesh (`/lore/nathd/INSTALLATION/omega_h-install/bin/Tomms_15ge_16me/mesh_15_16.osh`) on cranium through the new pumipic `test_revClass` and got the following results:

```
Time in rev class (omegah mesh) 0.627747 seconds
Ngraph global stats <vtx edges pins>: 2 1 1
done picparts
Time in rev class (pumipic->omegah mesh) 2.94779 seconds
```

`total_ments` and `n_gents` in omega_h were the same for both calls to `derive_revClass(2)`.  Likewise, the sizes of `l2lh` and `lh2h` are the same (`n_gents` and `total_ments`, respectively) going into the most expensive function `sort_by_high_index`.  

This is going to take some more digging to figure out where the 4x slow down is coming from.  I'm going to add a counter to see how many times `swap2` is called.  Different ordering of the picpart mesh may be hurting the sort.

On that point, I'm a bit concerned about the cost of the sort as we have more and more mesh entities classified on a single geometric model entity.

**Comment by cwsmith** [comment]
Writing the picpart mesh as an osh file, then loading that file into an omegah test that loads the mesh and calls `ask_revClass(2)` results in the poor performance.  This indicates that it is something specific to the picpart mesh that is causing the problem and not runtime problem (memory corruption, etc.) that is unique to the pumipic test.

**Comment by dhyan1272** [comment]
Maybe these issues are related.
https://github.com/SCOREC/omega_h/issues/22

**Comment by cwsmith** [comment]
> Maybe these issues are related.
> [SCOREC/omega_h#22](https://github.com/SCOREC/omega_h/issues/22)

Yes, these are essentially the same issues.  I'll modify the title of this one to make it clear that the focus of this issue has gone from performance to correctness.

**Comment by dhyan1272** [comment]
If I use classification information of the pumi-pic mesh to mark the list of mesh faces classified on the boundary it takes ``0.002 seconds!`` The algorithm:
```OMEGA_H_LAMDA(o::LO fid){
 if (exposed[fid])
  
} ```

**Comment by cwsmith** [comment]
We should be able to use the `set_ents(...)` function from Omega_h_mesh.hpp to create the topology with downward adjacency arrays (ents(dim)-to-verts) as done in `add_ents2verts(...)` in Omega_h_build.cpp and `read_internal` in Omega_h_meshsim.cpp.

**Comment by cwsmith** [comment]
A draft PR with explicit creation of entities in the picpart mesh is here:  https://github.com/SCOREC/pumi-pic/pull/79 

Running the reverse classification query on the input 150k mesh `mesh_15_16.osh` has the same performance as the query on the picpart mesh.  Prior to the fix, with incorrect classification, the time on the picpart mesh was [2.94779](https://github.com/SCOREC/pumi-pic/issues/75#issuecomment-900457801)

```
 $ ./test/test_revClass /lore/nathd/INSTALLATION/omega_h-install/bin/Tomms_15ge_16me/mesh_15_16.osh ignored
tag class_id 1
tag class_dim 1
dim size 4
0 0
1 0
2 30608
3 270059
Time in rev class (omegah mesh) 0.667262 seconds
Ngraph global stats <vtx edges pins>: 2 1 1
dim size 4
0 0
1 0
2 30608
3 270059
done picparts
Time in rev class (pumipic->omegah mesh) 0.603108 seconds
```

**Comment by cwsmith** [comment]
@dhyan1272 With this change all of our pumipic ctests are passing (at least the ones we expect to pass).  Would you please test gitrm with this branch when you get a chance?

**Comment by dhyan1272** [comment]
Sure I will let you know latest by tomorrow morning.

**Comment by dhyan1272** [comment]
The mesh information returned from a picparts mesh is correct.
I asked the number of mesh faces classified on a set of 14 geom ids (136964 mesh faces)
```
The csr ouput:
ptr size:15
data size: 136964
```
Time taken:
7.14372e-06 min
(Tested on an ~11.4 million mesh)

**Comment by cwsmith** [comment]
@dhyan1272 That looks good.  Thank you.  

Would you please run a few timesteps of gitrm using the branch?
