### ISSUE TITLE
adjacency search discussion

### ISSUE THREAD

**Issue by kumargp** [SCOREC/pumi-pic#8]
Put together the comments  collected from, 
https://github.com/SCOREC/GITRm/commit/90ae2decbd3dc68aee79527240d65d107b8738ec#commitcomment-31737194

**Flow** 
Process  all particles in an element (and all elements) in parallel, from a while loop.
All particles in an element start off with the element's closure data or state.
When elements are called in parallel, each element's lambda function splits the calls 
into that for particles. All the particles are running in parallel for a single step, asynchronously.
Adjacent element IDs are stored for further search of particles. 
Wait for the completion of the step. 
At this stage, particles are to be associated with these adjacent elements, but the particle data
are still with the source elements. 
Next step is a parallel reduction  per element, which  checks if all particles are found, or collision is detected. 
If any particle remains in any element, next parallel call starts processing all elements irrespective
of particles in it are all done or not.  But in the search kernel, only remaining particles are processed. 
Omega_h::Write data set are to be updated during the run. These will be replaced by 'particle_structures',
along with the for loop inside the lambda function distributing particles. 
Omega_h::parallel_reduce doesn't work. Kokkos functions to be used when Omega_h doesn't provide it.

**Comments by Cameron and replies**

>> Process  all particles in an element (and all elements) in parallel, from a while loop. All particles in an element start off with the element's closure data or state.

 > The particles don't store any element data; the elements store it.

GP: True, particles just use element data including fields and calculated stuff, not modify.

>>  When elements are called in parallel, each element's lambda function splits the calls into that for particles. All the particles are running in parallel for a single step, asynchronously.

> The number of threads per element will be a function of the SCS particle structure. It is highly unlikely
 that we will have one thread per particle. Until we have the macros added for the loop over elements
  and particles assume that there is only one 'thread' per element.

>> Adjacent element IDs are stored for further search of particles. 
Wait for the completion of the step. 

 > Is a step defined as one iteration of the outer while loop ? If so, it would be good to state that explicitly.

GP: Yes.

>> At this stage, particles are to be associated with these adjacent elements, but the particle data are still with the source elements. 

  >  Moving the particle's data between the arrays holding each elements particle data  after each iteration of the outer while loop may or may not be 'expensive'.  Until we have performance data that says it is a problem, I think we should   copy the particle's data from the previous parent element to the new  parent element after each iteration.
 >   The alternative (at least one) would be creating a 'temporary' list of  particles for each element and then either duplicating the coordinate information for those particles, or accessing the coordinates fro the 'first' parent element's particle structure which would be an irregular (non-coalesced) memory access. 

GP: Will implement this copying.

>> Next step is a parallel reduction  per element, which  checks if all particles are found, or collision is  detected. 

>  We can have a single bool didMove in kokkos 'global' memory that each thread  sets to true if it moves a particle from the first parent element.  This avoids atomics and is far cheaper (in both memory and compute) than the  reduction. At the beginning of each while loop iteration didMove is set to false.

GP:  Will implement this too.

>> If any particle remains in any element, next parallel call starts processing all elements irrespective
of particles in it are all done or not.  But in the search kernel, only remaining particles are processed. 

>  I'm not sure I understand this. In each while loop iteration all particles are checked to  see if they should be moved.  Are you proposing a way to indicate that they were previously checked?

GP: There is a gap between the base of the above text I wrote and your suggestion (I didn't catch it yesterday!) of keeping a global array. This was based on parallel reduction per element, which collects element-wise list of particles. The logic was that since there will be multiple particles typically to be processed per element, it will be efficient to start together all particles in an element, rather than iterating through the particles to be processed and starting a thread for each, from a to-be-moved (global) array.

**Comment by cwsmith** [comment]
Regarding the copying of particle data during the search:  We can't really do this until the SCS particle structure is added.  I assume you're going to put some temporary function to 'move' the single test particle? 

I don't follow the last point about the global array.  Note, there will not be a thread per particle - see the previous comment on the parallelism.  For now, let's just check all the particles in all the elements in each iteration.  Conditionals are not free on GPUs so it is sometimes faster to do the 'dumb' thing.

**Comment by cwsmith** [comment]
The pseudo push and search test https://github.com/SCOREC/pumi-pic/blob/9e553b64f7770a3f1e48df9337c6f8e7e29a04b6/test/pseudoPushAndSearch.cpp exercises particle move, search, and scs rebuild.
