### ISSUE TITLE
testing search and collision

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/pumi-pic#9]
Some ideas on a testing approach are below:

search driver
 - `./search <mdl> <mesh> <init coords> <final coords>`
 - write a helper function in driver that computes the element that contains the 'final coords' - this will be the reference solution we compare the result (destination element id) of the search algorithm to
 - test variants 2d, 3d, 2d w/coincident init, 2d w/coincident final, 3d w/coincident init, 3d w/coincident final
 - if it does not match `return 1`, otherwise `return 0`

wall collision driver
 - `./collison` # no arguments
 - hard a single tet into the driver and the initial and final particle position 
 - hard code the expected intersection point
 - run the collision/search routine and compare against expected value
  - if the collision point does not match `return 1`, otherwise `return 0`

**Comment by kumargp** [comment]
Added test files. Need to add ctest in CMakeLists.
Current assumption is that points on surface of mesh are not part of domain. Reason is the EField on surface is not realistic, and can't be used for pushing, I think. Also, once particle reaches surface, it is assumed as collided, or crossed the boundary.
This tolerance cases need to be handled carefully, by using epsilon in place of zero consistently. Now, testing by setting particle origin on surface may fail.

**Comment by cwsmith** [comment]
@kumargp Is this, or something like it, done?  Can this issue be closed?
